const THEMES = {
    "💡 Nápady / Startupy / Budoucnost": ["Změny nápadů", "Vzdělávací projekty",
        "Technologie", "AI / Future thinking", "Urbanistika", "Rozvoj měst", "Humanitární iniciativy"],
    "🤪 Humor / Lehká myšlenka": ["Ironie života", "Absurdismus",
        "Sarkasmus", "Tweety dne", "Kuriózní příběhy", "Svět memů"],
    "🧠 Věda / Fakta": ["Astronomie", "Biologie", "Filozofie",
        "Historická fakta", "Neurověda",
        "Sociologie", "Zajímavé výzkumy"],
    "💭 Osobní / Myšlenky": ["Otázky k sobě", "Sebereflexe",
        "Psychologie", "Vnitřní svět", "Motivace", "Deník myšlenek",
        "Myšlenky o životě", "Osobní příběhy"],
    "🧶 Koníčky / Volný čas": ["Úvahy v tichu", "DIY / Ruční práce",
        "Deskové hry 🎲", "Sport", "Kulinářství 🍳", "Cestování ✈️",
        "Knihy 📚"],
    "🔥 Aktuální / Společnost": ["Ekologie", "Lidská práva",
        "Vzdělávání", "Občanské iniciativy", "Ekonomika", "Politika",
        "Světové zprávy 🌍"],
    "📚 Historie / Kultura": ["Architektura", "Mýty a legendy", "Literatura",
        "Jazyk", "Kulturní dědictví", "Světová historie", "Ukrajinská historie"],
    "🎨 Kreativita / Umění": ["Animace", "Móda", "Divadlo", "Filmy / Seriály 🎬",
        "Hudba 🎧", "Design", "Fotografie 📷", "Ilustrace 🎨"],
    "❤️ Komunita / Interakce": ["Otázky ostatním", "Rady",
        "Seznámení","Odpovědi na myšlenky",
        "Ankety", "Diskuse"],
};

export default THEMES;
